### ISSUE TITLE
Wrong binding on OS X?

### ISSUE THREAD

**Issue by tomasdev** [ronomon/utimes#3]
Installed using `npm install --save-exact @ronomon/utimes` today.
```
dyld: lazy symbol binding failed: Symbol not found: __ZN4node19GetCurrentEventLoopEPN2v87IsolateE
  Referenced from: /Users/trogg1/Desktop/X/Y/node_modules/@ronomon/utimes/binding.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN4node19GetCurrentEventLoopEPN2v87IsolateE
  Referenced from: /Users/trogg1/Desktop/X/Y/node_modules/@ronomon/utimes/binding.node
  Expected in: flat namespace
```

May be related to https://github.com/kelektiv/node.bcrypt.js/issues/656 ?

I did try re-building. Nothing changed. Using version 2.3.1

**Comment by jorangreef** [comment]
Thanks @tomasdev 

Yes, it just means there's a mismatch between Node or Nan's ABI and you need to rebuild or upgrade Node or Nan.

You might have another module which is using an older version of Nan.

Try reinstalling @ronomon/utimes in a completely separate directory, you should see that it works. I just tested again on OS X and `npm install --save-exact @ronomon/utimes` works fine.

See: https://stackoverflow.com/questions/30130692/dyld-lazy-symbol-binding-failed-symbol-not-found-node-module-register
