### ISSUE TITLE
Can the callback return custom data?

### ISSUE THREAD

**Issue by soubhikchatterjee** [ronomon/utimes#4]
Hi @ronomon

Thanks for the wonderful library. I am using it in one of my nodejs project.

I am using utime to change a modified date of 1000+ files of multiple albums and this is happening all in a loop so chances are that the callback of a file is executed after x seconds/minutes.

Is there anyway I can pass some custom data along with the callback function? For eg I want such that when the callback executes it tells me which album the file belonged to and other meta data of the album.

Thanks

**Comment by jorangreef** [comment]
Thanks @soubhikchatterjee 

You can do that already with Javascript by just using a closure, for example:

```javascript
function CustomUtimes(path, btime, mtime, atime, custom, callback) {
  Utimes.utimes(path, btime, mtime, atime,
    function(error) {
      callback(error, custom);
    }
  );
}
```

The closure created for the anonymous callback function in `CustomUtimes()` will hold onto whatever custom data you pass it, until it calls your callback.

**Comment by soubhikchatterjee** [comment]
Perfect!

Thanks
