### ISSUE TITLE
Parameters are not Unix but Js milisecondn timestamps

### ISSUE THREAD

**Issue by actuallymentor** [ronomon/utimes#5]
Hello @ronomon,

Thanks for the useful module.

The parameters in your package respond well to `new Date(yyyy-mm-dd).getTime()` formatted miliseconds, but those are not strictly Unix timestamps as those are found by `new Date(yyyy-mm-dd).getTime() / 1000`.

I would recommend editing the Readme.

Would you like me to do a pull-request?

Edit: typo

**Comment by jorangreef** [comment]
Thanks @actuallymentor 

> those are not strictly Unix timestamps as those are found by new Date(yyyy-mm-dd).getTime() / 1000

No, that's how Node's API works, and `new Date(yyyy-mm-dd).getTime() / 1000` is not in fact a Unix timestamp as you suggest.

The [Wikipedia article on Unix time](https://en.wikipedia.org/wiki/Unix_time#Definition) actually defines a Unix timestamp as:

```
Unix time (also known as POSIX time[citation needed] or UNIX Epoch time[1]) is a system
for describing a point in time. It is the number of seconds that have elapsed since
00:00:00 Thursday, 1 January 1970,[2] Coordinated Universal Time (UTC), minus leap
seconds.
```

This is the same as calling `Date.now()` in Javascript.

In fact, the @ronomon/utimes README already mentions under [Usage](https://github.com/ronomon/utimes#usage) that the module accepts Unix millisecond timestamps:

```
Timestamps btime, mtime, atime should be passed as Unix millisecond timestamps
```

I hope this addresses your issue?

**Comment by actuallymentor** [comment]
Hmm weird, I guess I've been misinformed by [this SO thread](https://stackoverflow.com/questions/11893083/convert-normal-date-to-unix-timestamp).

Thanks for the clarification.
