### ISSUE TITLE
Maintained ?

### ISSUE THREAD

**Issue by Offirmo** [ronomon/utimes#9]
Hi,

this module looks awesome... too bad it's no longer working.

Should we expect some maintenance or did you move on to other things?

Thanks.

**Comment by jorangreef** [comment]
Thanks @Offirmo 

You should expect some maintenance.

I would like to upgrade to N-API and this will take a few weeks.

All the best.

**Comment by Offirmo** [comment]
Thanks @jorangreef .

This level of complexity + multiple OS support is clearly above the usual npm module.

This hard work should be rewarded. Do you have a "buy me a coffee" or any other support page?

**Comment by jorangreef** [comment]
I appreciate your support and encouragement.

I usually redirect people to support the ziglang project, which is fantastic:

https://github.com/sponsors/andrewrk

**Comment by Jule-** [comment]
> Thanks @Offirmo
> 
> You should expect some maintenance.
> 
> I would like to upgrade to N-API and this will take a few weeks.
> 
> All the best.

@jorangreef Have you ever see my PR #8? 🤔 I have already done that for you... Can you take a look into it and maybe merge it?!
